name: peerqr
description: A new Flutter project.
homepage: https://github.com/avyudaya1/peerqr
repository: https://github.com/avyudaya1/peerqr
issue_tracker: https://github.com/avyudaya1/peerqr/issues
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # For custom localizations

  hive: ^2.0.5
  provider: ^6.0.2

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/